#! /bin/sh

bspc config border_width        0
bspc config window_gap         10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config top_padding	14

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Google-chrome-stable desktop=^2 follow=on
bspc rule -a vlc desktop=^3 follow=on
bspc rule -a libreoffice desktop=^4 follow=on
bspc rule -a Firefox desktop=^3 follow=on
bspc rule -a Rstudio-bin desktop=^4 follow=on
bspc rule -a Screenkey manage=off
